### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by openStove** [mschm/node-red-contrib-binary#1]
Hi More a feature request than a bug... ;-)

Could you just add a small example in the doc ?

For example having a binary containing  a text and a number, what would be the parser synthax, that would help alot ... 

Thanks for your great work

**Comment by mschm** [comment]
Hi, sorry for keeping you waiting! Check out the example that @dceejay has contributed...

**Comment by Dinotoh1971** [comment]
Hi, is this node also able to convert an array to a buffer?

I have problem creating dynamic size buffer, was thinking of using dynamic array to pass through this node to create dynamic buffer but do not know how to put the syntax into the pattern.

Thank you in advance.

**Comment by Dinotoh1971** [comment]
Please ignore my request, actually it can just put the array in the buffer declaration to create the dynamic buffer if the array is dynamic.
