### ISSUE TITLE
10 bit integer returning zeroes for last four bits

### ISSUE THREAD

**Issue by iVolt1** [mschm/node-red-contrib-binary#12]
Hi.  I have good grasp of what this node can do and it will be very useful for a Node-red 3.02 project I am working on, so thanks for creating this.

The problem I am having is the 10 bit integer that is returned for 'type' appears to return the last four bits a zeroes so the value is up to 17 decimal less that it should be.  I am confident in the actual values as they have been been returned from the serial port and converted in javascript function in node-red as the correct 'type' value for years.

The buffer for this example:
[0,63,0,0,0,0,158,12,84,0]

The binary node confiruration:
l8 => service,
l8 => port,
l32 => timestamp,
l32{x2, b10 => type, x20} 

The json returned
{"service":202,"port":11,"timestamp":2281766913,"type":816}

Expected value:
x337 dec 823
001100110111

Returned value:
x330 dec 816
001100110000 

Example flow with a different buffer:

[{"id":"9882812903f1401f","type":"tab","label":"Flow 9","disabled":false,"info":"","env":[]},{"id":"7a609bcd384ab141","type":"inject","z":"9882812903f1401f","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[202,14,1,0,2,3,129,29,1,38,240,158,4,0,35,242,5,133,53]","payloadType":"bin","x":210,"y":100,"wires":[["866d1a00dc465069","d09f72fc38dd5c57"]]},{"id":"866d1a00dc465069","type":"function","z":"9882812903f1401f","name":"Set Message Type","func":"// Create new array to hold array with indices that match ruby code and load it from msg.payload array.\nlet data_in = [];\nvar bufferLength = msg.payload.length - 3\nfor (let i = 0; i < bufferLength; i++) {\n  data_in[i] = msg.payload[i + 3]\n} \n// Get the message id and set the msg.topic to it.\nvar header = (data_in[6] << 24) | (data_in[7] << 16) | (data_in[8] <<  8) | (data_in[9]);\nvar message_id = ((header >> 20) & 0x3FF).toString(16);\nmsg.topic = message_id;\nmsg.payload = (header >> 20) & 0x3FF;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":430,"y":100,"wires":[["43f54a5646b52bc3"]]},{"id":"43f54a5646b52bc3","type":"debug","z":"9882812903f1401f","name":"debug 47","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":660,"y":100,"wires":[]},{"id":"d09f72fc38dd5c57","type":"binary","z":"9882812903f1401f","name":"bin","property":"payload","pattern":"l8 => service,\nl8 => port,\nl32 => timestamp,\nl32{x2, b10 => type, x20} \n\n","x":390,"y":160,"wires":[["9b21d723231aafb2"]]},{"id":"9b21d723231aafb2","type":"debug","z":"9882812903f1401f","name":"debug 48","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":660,"y":160,"wires":[]}]

Thanks for any help or bug fixing.

**Comment by dceejay** [comment]
most folk now use the [node-red-contrib-buffer-parser](https://flows.nodered.org/node/node-red-contrib-buffer-parser) as it is a lot more configurable and easier to set up :-)

Plus if I use the buffer you give as an example [0,63,0,0,0,0,158,12,84,0] it doesn't match either the expected or return values you then show... so needs some clarification.

If I run your flow - and correct the input buffer to only be 10 bytes long - ie [202,14,1,0,2,3,129,29,1,38] - then both your function and the node give type 608.

Here is my example that includes the buffer parser node version as well
```
[{"id":"d7ba72d9e06c924c","type":"inject","z":"9882812903f1401f","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[202,14,1,0,2,3,129,29,1,38]","payloadType":"bin","x":190,"y":560,"wires":[["c21643c8f97ebbc9","3a76d64bba04939c","655fb0e4c850653a"]]},{"id":"c21643c8f97ebbc9","type":"function","z":"9882812903f1401f","name":"Set Message Type","func":"// Create new array to hold array with indices that match ruby code and load it from msg.payload array.\nlet data_in = [];\nvar bufferLength = msg.payload.length - 3\nfor (let i = 0; i < bufferLength; i++) {\n data_in[i] = msg.payload[i + 3]\n} \n// Get the message id and set the msg.topic to it.\nvar header = (data_in[6] << 24) | (data_in[7] << 16) | (data_in[8] << 8) | (data_in[9]);\nvar message_id = ((header >> 20) & 0x3FF).toString(16);\nmsg.topic = message_id;\nmsg.payload = (header >> 20) & 0x3FF;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":410,"y":560,"wires":[["66aec1764b19b67a"]]},{"id":"66aec1764b19b67a","type":"debug","z":"9882812903f1401f","name":"debug 47","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":620,"y":560,"wires":[]},{"id":"3a76d64bba04939c","type":"binary","z":"9882812903f1401f","name":"bin","property":"payload","pattern":"l8 => service,\nl8 => port,\nl32 => timestamp,\nl32{x2, b10 => type, x20} \n\n","x":370,"y":620,"wires":[["a4d2ce956a859872"]]},{"id":"a4d2ce956a859872","type":"debug","z":"9882812903f1401f","name":"debug 48","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":620,"y":620,"wires":[]},{"id":"655fb0e4c850653a","type":"buffer-parser","z":"9882812903f1401f","name":"","data":"payload","dataType":"msg","specification":"spec","specificationType":"ui","items":[{"type":"uint8","name":"service","offset":0,"length":1,"offsetbit":0,"scale":"1","mask":""},{"type":"uint8","name":"port","offset":1,"length":1,"offsetbit":0,"scale":"1","mask":""},{"type":"int32le","name":"timestamp","offset":2,"length":1,"offsetbit":0,"scale":"1","mask":""},{"type":"int32le","name":"type","offset":6,"length":1,"offsetbit":0,"scale":">>>20","mask":"0x3ff00000"}],"swap1":"","swap2":"","swap3":"","swap1Type":"swap","swap2Type":"swap","swap3Type":"swap","msgProperty":"payload","msgPropertyType":"str","resultType":"keyvalue","resultTypeType":"return","multipleResult":false,"fanOutMultipleResult":false,"setTopic":true,"outputs":1,"x":390,"y":680,"wires":[["af1dc0a6c10e1247"]]},{"id":"af1dc0a6c10e1247","type":"debug","z":"9882812903f1401f","name":"debug 51","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":620,"y":680,"wires":[]}]
```

**Comment by iVolt1** [comment]
Thanks for the quick reply dceejay.  I did try buffer-parser yesterday and got the same results as binary.  I do like the simplicity of binary but may have use for both of those.  I need the whole buffer packet, not just the portion that gets the mesageid so I am continuing to sort things out and will reply back here with an update.

**Comment by iVolt1** [comment]
I have it all sorted it out now.  It was mostly a matter of getting my input buffer correct as you showed.  I am glad to have a good handle on both binary and packet as my project progreseses.   Thanks again!
