### ISSUE TITLE
Enhancement request - allow msg.payload to be an array of numbers

### ISSUE THREAD

**Issue by shrickus** [mschm/node-red-contrib-binary#7]
I'm trying to do something that should be simple:

msg.payload is an array of two 16bit integers -> [ 17269, 31688 ]
I would like to convert those to a single 32bit float, but it throws "Error: invalid input"

In looking through the code, it appears that the array is being treated as an object, and is passed to the serializer, where the error occurs. Should an array of numbers be able to be serialized as valid input?

**Comment by bohtho** [comment]
And even allow msg.payload be a string representation of binary data. That would be handy.

**Comment by dceejay** [comment]
Strings now accepted - 71827e792bdd3daa0df05b360d68a612fa64275c
