### ISSUE TITLE
MCP9808 Need a little help here.

### ISSUE THREAD

**Issue by vlturner** [mschm/node-red-contrib-binary#9]
![image](https://user-images.githubusercontent.com/38079120/71597245-41f3b200-2af7-11ea-8270-6f90e04f5688.png)

Need help to define around this for MCP9808 Temp sensor. I keep getting errors.

**Comment by vlturner** [comment]
Here is the Node-Red

[{"id":"bc2f721.febbc9","type":"debug","z":"c3b24910.186f48","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1040,"y":690,"wires":[]},{"id":"dcf324d9.e92d","type":"i2c in","z":"c3b24910.186f48","name":"","address":"24","command":"05","count":"2","x":530,"y":690,"wires":[["ee77bc84.8c5e28"]]},{"id":"bab5144c.a64ad8","type":"ui_button","z":"c3b24910.186f48","name":"Pull Temperature","group":"b38ae774.a9b6e","order":0,"width":0,"height":0,"passthru":true,"label":"Pull Temperature","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"bin","topic":"","x":330,"y":690,"wires":[["dcf324d9.e92d"]]},{"id":"ee77bc84.8c5e28","type":"binary","z":"c3b24910.186f48","name":"Temperature Conversion","property":"payload","pattern":"b16{b3,b1,b12}","x":790,"y":690,"wires":[["bc2f721.febbc9"]]},{"id":"59b60ed1.3a98c","type":"inject","z":"c3b24910.186f48","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":300,"y":650,"wires":[["dcf324d9.e92d"]]},{"id":"b38ae774.a9b6e","type":"ui_group","z":"","name":"Buttons","tab":"91b245b1.b4ed7","order":2,"disp":true,"width":"6","collapse":false},{"id":"91b245b1.b4ed7","type":"ui_tab","z":"","name":"I2C","icon":"dashboard","order":3,"disabled":false,"hidden":false}]

**Comment by vlturner** [comment]
Here is what the sensor returns

0: 0xc1
1: 0xa4

**Comment by dceejay** [comment]
You are almost there - you just need to assign the various parts to field names - for example
```
[{"id":"4c264140.705c","type":"debug","z":"c4f68fc3.2dd88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":420,"wires":[]},{"id":"36f8ce45.b63f52","type":"binary","z":"c4f68fc3.2dd88","name":"Temperature Conversion","property":"payload","pattern":"b16{b3 => flags,b1 => sign,b12=>temperature} ","x":570,"y":420,"wires":[["4c264140.705c"]]},{"id":"aab6c33b.79e4","type":"function","z":"c4f68fc3.2dd88","name":"","func":"msg.payload = Buffer.from([0xc1,0xa4])\nreturn msg;","outputs":1,"noerr":0,"x":320,"y":420,"wires":[["36f8ce45.b63f52"]]},{"id":"254b6c31.427d74","type":"inject","z":"c4f68fc3.2dd88","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":420,"wires":[["aab6c33b.79e4"]]}]
```
Gives me a payload of 
![image](https://user-images.githubusercontent.com/5375409/71602023-1354f600-2b4e-11ea-8a8a-9203d8d63607.png)
